[build]
  command = "npm run build"
  publish = "dist"
  [[redirects]]
  from = "/*/*"
  to = "/"
  status = 200
  force = false
  [[redirects]]
    from = "/profile/*"
    to = "/"
    status = 200
    force = false
